// ex 11.1

// write a program that writes a character and integer a type double and two string objects to a disc file
// Write another program that reads the file generated by the above program by using an " ifstream" object.

#include <iostream>
#include <fstream>
using namespace std;
int main()
{
    char ch = 'x';
    int j = 87;
    double d = 6.99;
    char str1[] = "oops";
    char str2[] = " Programming";
    ofstream out("data.txt");
    out << ch << j << d << str1 << str2 << endl;
    cout << "File Written";
    return 0;
}